//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Cudotosi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Cudotosi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cudotosi.
        /// </summary>
        internal static string CudotosiWindowName {
            get {
                return ResourceManager.GetString("CudotosiWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cudotosi.
        /// </summary>
        internal static string CudotosiWindowTitle {
            get {
                return ResourceManager.GetString("CudotosiWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultImage {
            get {
                object obj = ResourceManager.GetObject("DefaultImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target file was saved.
        /// </summary>
        internal static string NoTargetFileWasSaved {
            get {
                return ResourceManager.GetString("NoTargetFileWasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the top left position of the area that will be cut out.
        /// </summary>
        internal static string PleaseClickTopLeft {
            get {
                return ResourceManager.GetString("PleaseClickTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file could not be saved.
        /// </summary>
        internal static string TargetFileCouldNotBeSaved {
            get {
                return ResourceManager.GetString("TargetFileCouldNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file &quot;{0}&quot; already exists. Overwrite?.
        /// </summary>
        internal static string TargetFileExistsOverwrite {
            get {
                return ResourceManager.GetString("TargetFileExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file &quot;{0}&quot; was saved.
        /// </summary>
        internal static string TargetFileSaved {
            get {
                return ResourceManager.GetString("TargetFileSaved", resourceCulture);
            }
        }
    }
}
